kind: Deployment
apiVersion: apps/v1
metadata:
  name: todoapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp-backend
  template:
    metadata:
      labels:
        app: todoapp-backend
    spec:
      containers:
        - name: todoapp-backend
          image: asia-northeast1-docker.pkg.dev/phu-le-it/devops-cicd-repository/todoapp-backend:v1.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
