kind: Deployment
apiVersion: apps/v1
metadata:
  name: todoapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp-frontend
  template:
    metadata:
      labels:
        app: todoapp-frontend
    spec:
      containers:
        - name: todoapp-frontend
          image: asia-northeast1-docker.pkg.dev/phu-le-it/devops-cicd-repository/todoapp-frontend:v1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
